# Generated by Django 5.1.6 on 2025-03-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('users', '0002_lectureuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lectureuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='users.lectureuser'),
        ),
    ]
